# Generated by Django 3.0.5 on 2020-04-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_topic2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic2',
        ),
    ]
