# Generated by Django 3.0.5 on 2020-04-21 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_delete_topic2'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.TextField(default='0000000', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(default='0000000', editable=False, max_length=200),
        ),
    ]
